### ISSUE TITLE
Mainly every single issue i can find with this project.

### ISSUE THREAD

**Issue by StoneMcYT** [Avdan-OS/AvdanOS#3]
Look mods hear me out before you ban me from existence but I have noticed many recurring issues in this project.
- Not using GitHub as a main. Last time I checked this is a coding-based project where we need to keep track of bugs, features, other code etc which cant be done in a discord setting 
Fix: Move suggestions and issues to Github and make templates for those on every repo 
-  2 roadmaps that make no sense
Fix: Remove 1 of the roadmaps (Readme.md) and port stuff over to the other (Github projects)
-  Lack of templates 
Fix: Add Github templates
- Broken roles I was made a 'temp admin' for a 1 day and I still have the owner discord perm haha
Fix: Fix the GH teams configuration 
- Cringy branch stuff like seriously what is this
![image](https://user-images.githubusercontent.com/67421882/169707620-01abc733-34cd-4217-a159-c281155028e8.png)
Fix: Delete the spam branches and make naming standards 
~~- No actual standards. Dev app just lets anyone in without properly filtering people~~ - Removed as someone notified me on how the application process was recently updated 
- Docs seem kind empty
Fix: Have documentation/wiki 
- Discord automod is wack
Come on it took you guys forever to turn on slow mode to prevent spammers
Fix: Just be more proactive with moderation

**Comment by StoneMcYT** [comment]
This is basically from an outsiders perspective and from what I've got from the first few days in the project

**Comment by froxcey** [comment]
> Not using GitHub as a main. Last time I checked this is a coding-based project where we need to keep track of bugs, features, other code etc which cant be done in a discord setting

Both should be used, as of now. Discord is more robust. Since this project's size is currently small, Discord works really well. People can do discussions and suggestions fast. When the project scales up, Github should become the main and Discord should become less important. I do agree with the issue templates, repos need to have a better setup.

> Cringy branch stuff like seriously what is this

Now that's very wrong. So many branches, what a messy tree. [Someone clean it up pls](https://github.com/Avdan-OS/Desktop-environment/branches)

> Docs seem kind empty

Not now

**Comment by StoneMcYT** [comment]
> > Not using GitHub as a main. Last time I checked this is a coding-based project where we need to keep track of bugs, features, other code etc which cant be done in a discord setting
> 
> Both should be used, as of now. Discord is more robust. Since this project's size is currently small, Discord works really well. People can do discussions and suggestions fast. When the project scales up, Github should become the main and Discord should become less important. I do agree with the issue templates, repos need to have a better setup.


Well discord for quick discussions yes I but in my opinion github should be used for tracking major suggestions as well as bugs

**Comment by StoneMcYT** [comment]
Okay since ive been elected as CM im gonna work towards solving all of this
