### ISSUE TITLE
Boot screen improvement

### ISSUE THREAD

**Issue by Padmanabh82** [Avdan-OS/AvdanOS#4]
so someone please remove the logs that come while booting
https://user-images.githubusercontent.com/70370670/169805311-52d1f3e9-90de-4582-80bf-1c78a8c9487a.mp4

user should only see booting animation.
so anyone can comment who can do this assignment, I will assign this issue to you

**Comment by donthaveaneme** [comment]
i think, we can make a choice whether the user wants to see or hide it, but we can make it hide by default. so its not really look cluttered, and has a lot of customization...

**Comment by Padmanabh82** [comment]
@donthaveaneme yeah, i think to make shortcut for viewing it

**Comment by Padmanabh82** [comment]
I created it on wrong repo
