### ISSUE TITLE
Problem with minimized windows

### ISSUE THREAD

**Issue by Rish-creator** [Avdan-OS/AvdanOS#5]
*This is based on the latest website demo of Avdan Os*
What I have noticed is that the minimized windows become a list of horizontal stack just above a taskbar. 
![Screenshot 2022-05-28 185417](https://user-images.githubusercontent.com/74548430/170827492-9a9edecd-157e-42bb-bcb8-6b230c86e2aa.jpeg)
Well as in the picture, once you open enough tabs, it becomes unusable. So one way I think to solve this is to add a separater just after the pinned/default apps and then showing all the open apps (upto 4 at one time) and at the end, keeping two slim buttom, up and down showing the other open apps. 

Feature suggestion: When hovered over the icons, a small thumbnail should appear. Like in windows Os

**Comment by HelaPortal** [comment]
I think it will get fixed once the real version comes out, i dont think they update the preview anymore.
